name: Auto update Changes

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: wows_data

    - name: Run script
      run: |
        python update_ships.py ${{ secrets.APPLICATION_ID }}
      working-directory: wows_data

    - name: Commit and push changes if any
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./wows_data
        keep_files: false
        allow_empty_commit: true
        enable_jekyll: true
        commit_message: ${{ github.event.head_commit.message }}
        full_commit_message: ${{ github.event.head_commit.message }}
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        destination_dir: ./wows_data
        publish_branch: main

